name: Auto Commit

on:
  schedule:
    - cron: '17 3 * * *'     # هر روز 03:17 UTC
    - cron: '17 15 * * *'    # هر روز 15:17 UTC
  workflow_dispatch:          # امکان اجرای دستی

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update activity log
        run: |
          echo "Update: $(date -u)" >> activity.log

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add activity.log
          git commit -m "chore: automated update $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
