name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'   # هر روز ساعت 12 UTC اجرا میشه
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # خیلی مهم: credentials پیش‌فرض غیرفعال میشه

      - name: Make change
        run: |
          echo "Update on $(date -u)" >> update.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update.txt
          git commit -m "chore: auto commit - $(date -u)" || echo "No changes to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
